/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.zeninfor.chager;

import com.zeninfor.tool.StringUtils;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author WY
 */
public class LogFrame extends javax.swing.JFrame {

    /**
     * Creates new form LogFrame
     */
    public LogFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        butLogClean = new javax.swing.JButton();

        setName("logframe"); // NOI18N

        logTextArea.setColumns(20);
        logTextArea.setFont(new java.awt.Font("宋体", 0, 13)); // NOI18N
        logTextArea.setRows(5);
        logTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        logTextArea.setEnabled(false);
        logTextArea.setFocusable(false);
        jScrollPane1.setViewportView(logTextArea);

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        butLogClean.setBackground(new java.awt.Color(204, 204, 204));
        butLogClean.setText("清 除");
        butLogClean.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butLogClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLogCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(553, Short.MAX_VALUE)
                .addComponent(butLogClean)
                .addGap(537, 537, 537))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(butLogClean)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butLogCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLogCleanActionPerformed
        // TODO add your handling code here:
        this.logTextArea.setText("");
        logs.clear();
    }//GEN-LAST:event_butLogCleanActionPerformed

    
    
    /**
     * 设置日志信息
     * @param log
     */
    public void addLogTxt(String log){
        log = StringUtils.getStringDate()+" - "+ log;
        //判断当前日志条数，保留最近500条
        logs.add(0,log);
        StringBuilder txt = new StringBuilder();
        //多的删除
        if(logs.size() > 500){
            for(int i = 500; i < logs.size() ;i++){
                logs.remove(i);
            }
        }
        logs.stream().forEach((item) -> {
            txt.append(item).append("\n");
        });
        
        this.logTextArea.setText(txt.toString());
    }
    
    
     //日志数据集合
    List<String> logs = new ArrayList<>();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butLogClean;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logPanel;
    private javax.swing.JTextArea logTextArea;
    // End of variables declaration//GEN-END:variables
}
